[package]
name = "rust-rpg"
description = "A Rustlang based Rougelike RPG"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
text_io = "0.1.7"